Part A — EDA and preprocessing

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix


credit_data = pd.read_csv("credit_applicants.csv")


features = ["monthly_income_inr", "credit_utilization_ratio", "existing_loans_count"]

# If your code named the score column slightly differently, it will auto-add it safely here
score_col = "credit_score" if "credit_score" in credit_data.columns else "cibil_score" if "cibil_score" in credit_data.columns else "credit_bureau_score" if "credit_bureau_score" in credit_data.columns else None

if score_col:
    features.append(score_col)

# Define inputs (X) and target answer labels (y)
X = credit_data[features].copy()
y = credit_data["default"]

# 3. Train-Test Split: 80% to train the models, 20% to test their accuracy
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

# 4. Fill in missing scores safely using the training median to prevent data leakage
if score_col:
    train_median = X_train[score_col].median()
    X_train[score_col] = X_train[score_col].fillna(train_median)
    X_test[score_col] = X_test[score_col].fillna(train_median)

# =========================================================================
# MODEL A TRAINING: LOGISTIC REGRESSION
# =========================================================================
print("=== METRIC REPORTS FOR MODEL A: LOGISTIC REGRESSION ===")
lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train, y_train)

# Generate test predictions and display matrix grids
y_pred_lr = lr_model.predict(X_test)
print("\nConfusion Matrix Grid:")
print(confusion_matrix(y_test, y_pred_lr))
print("\nClassification Score Logs:")
print(classification_report(y_test, y_pred_lr))

print("-" * 65)

# =========================================================================
# MODEL B TRAINING: DECISION TREE CLASSIFIER
# =========================================================================
print("\n=== METRIC REPORTS FOR MODEL B: DECISION TREE CLASSIFIER ===")
dt_model = DecisionTreeClassifier(max_depth=5, random_state=42)
dt_model.fit(X_train, y_train)

# Generate test predictions and display matrix grids
y_pred_dt = dt_model.predict(X_test)
print("\nConfusion Matrix Grid:")
print(confusion_matrix(y_test, y_pred_dt))
print("\nClassification Score Logs:")
print(classification_report(y_test, y_pred_dt))

Part B — Classification models

import numpy as np
import pandas as pd

# 1. Open your generated applicants file
df_pricing = pd.read_csv("credit_applicants.csv")

# 2. Add an empty column for Interest Rates and Risk Tiers
risk_tiers = []
interest_rates = []

# 3. Use a basic loop to assign tiers row-by-row based on your data metrics
# (We look at credit scores and if they are a default risk)
for index, row in df_pricing.iterrows():
    # If the score is missing or very low, or they are flagged as a default risk
    if pd.isna(row['credit_bureau_score']) or row['credit_bureau_score'] < 550 or row['default'] == 1:
        risk_tiers.append("Tier 4 (Highest Risk)")
        interest_rates.append("24.00%")
    elif row['credit_bureau_score'] >= 550 and row['credit_bureau_score'] < 650:
        risk_tiers.append("Tier 3 (Medium-High Risk)")
        interest_rates.append("16.00%")
    elif row['credit_bureau_score'] >= 650 and row['credit_bureau_score'] < 750:
        risk_tiers.append("Tier 2 (Medium-Low Risk)")
        interest_rates.append("12.00%")
    else:
        risk_tiers.append("Tier 1 (Lowest Risk)")
        interest_rates.append("8.00%")

# 4. Save these lists back into our spreadsheet as new columns
df_pricing["Assigned Risk Tier"] = risk_tiers
df_pricing["Assigned Interest Rate"] = interest_rates

# 5. Display the top 5 rows to confirm it works perfectly!
df_pricing[["applicant_id", "credit_bureau_score", "default", "Assigned Risk Tier", "Assigned Interest Rate"]].head()

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import IsolationForest

# 1. Load the transaction behavior file generated by your script
df_behavior = pd.read_csv("txn_behaviour.csv")

# 2. Select only the numeric columns our algorithm needs to look at
features_to_use = ["txn_hour", "is_new_device", "txn_amount_inr"]
X_behavior = df_behavior[features_to_use]

# 3. Standardize the data numbers (this shrinks them so the algorithm reads them easily)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_behavior)

# 4. Configure scikit-learn's Isolation Forest algorithm
# We set the contamination to 5.7% to match your professor's exact mathematical rule
iso_forest = IsolationForest(contamination=0.057, random_state=42)

# Run the algorithm to flag anomalies (-1 means anomaly, 1 means safe)
df_behavior["predicted_anomaly"] = iso_forest.fit_predict(X_scaled)

# 5. Perform the Professor's required Recall Check!
# We extract the 15 true hidden attack rows (where transaction_id starts with 'BTXNA')
true_anomalies = df_behavior[df_behavior["txn_id"].str.startswith("BTXNA")]

# Count how many of those 15 rows our algorithm successfully caught (predicted as -1)
caught_count = (true_anomalies["predicted_anomaly"] == -1).sum()

print("=== ISOLATION FOREST ANOMALY PERFORMANCE LOG ===")
print(f"Total hidden attacks seeded in data:    15 rows")
print(f"Total hidden attacks successfully CAUGHT: {caught_count} rows")
print(f"True Detection Recall Rate:             {(caught_count / 15) * 100:.2f}%")

Part C — Anomaly detection and optional segmentatio

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# 1. Load the applicant profiles dataset
df_apps = pd.read_csv("credit_applicants.csv")

# 2. Select the numeric features to find behavioral groups
cluster_features = ["monthly_income_inr", "credit_utilization_ratio", "existing_loans_count"]
X_cluster = df_apps[cluster_features].copy()

# 3. Handle any blanks and scale the numbers so they match perfectly
X_cluster = X_cluster.fillna(X_cluster.median())
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_cluster)

# 4. Run K-Means with an optimal k=3 behavioral groups
kmeans = KMeans(n_clusters=3, random_state=42, n_init=10)
df_apps["Behavior_Cluster"] = kmeans.fit_predict(X_scaled)

# 5. Check if any group over-indexes (has a higher rate) on defaults!
cluster_analysis = df_apps.groupby("Behavior_Cluster")["default"].mean() * 100

print("=== K-MEANS CUSTOMER SEGMENTATION RESULTS ===")
for cluster_num, default_rate in cluster_analysis.items():
    print(f"Group/Cluster {cluster_num}: Average Default Risk Rate is {default_rate:.2f}%")
